import {
  LARGE_SCREEN_SIZE,
  MEDIUM_SCREEN_SIZE,
  SMALL_SCREEN_SIZE,
} from './ScreenSize';
import {
  NUMBER_CARDS_SCREEN_1280,
  NUMBER_CARDS_SCREEN_768,
  NUMBER_CARDS_SCREEN_320,
  PAGINATION_CARDS_1280,
  PAGINATION_CARDS_768,
  PAGINATION_CARDS_320,
} from './constants';

export const limitsByScreenSize = {
  [LARGE_SCREEN_SIZE]: {
    limit: NUMBER_CARDS_SCREEN_1280,
    paginationLimit: PAGINATION_CARDS_1280,
  },
  [MEDIUM_SCREEN_SIZE]: {
    limit: NUMBER_CARDS_SCREEN_768,
    paginationLimit: PAGINATION_CARDS_768,
  },
  [SMALL_SCREEN_SIZE]: {
    limit: NUMBER_CARDS_SCREEN_320,
    paginationLimit: PAGINATION_CARDS_320,
  },
};
